# This type stub file was generated by pyright.

# 第三方无类型包（PyExecJS）__main__ 的最小存根；参数类型由 argparse 推断为
# 动态类型，故放宽本文件相关严格检查。
# pyright: reportGeneralTypeIssues=none, reportMissingParameterType=none, reportUnknownParameterType=none, reportImplicitOverride=none

from argparse import Action
from typing import Any

class PrintRuntimes(Action):
    def __init__(self, option_strings: list[str], dest: str = ..., default: Any = ..., help: str | None = ...) -> None: ...
    def __call__(self, parser: Any, namespace: Any, values: Any, option_string: str | None = ...) -> None: ...

def main() -> None: ...

if "__main__" == __name__:
    ...
