# This type stub file was generated by pyright.

# 第三方无类型包（PyExecJS）的最小存根；抽象类以 metaclass=ABCMeta 声明（非继承 ABC）。
# 上游源码用 @six.add_metaclass(ABCMeta)（Py2 兼容写法）套元类，但 six 不带 py.typed，
# 存根 import 它就会被按单文件检查的 mypy（IDE 语言服务）报 [import-untyped]。改成本等价的
# metaclass= 写法即可根除：不必新增 types-six 依赖，也不必整文件 disable 该错误码（那会连带
# 屏蔽本文件今后引入的其它无存根导入）。等价性实测：两种写法下 mypy 同样把本类判为抽象类
# （未实现 is_available 就实例化，照样报 [abstract]）。

from abc import ABCMeta, abstractmethod
from typing import Any

class AbstractRuntimeContext(metaclass=ABCMeta):
    # Abstract base class for runtime context class.
    def exec_(self, source: str) -> str:
        # Execute source by JavaScript runtime and return all output to stdout as a string.
        #
        # source -- JavaScript code to execute.
        ...

    def eval(self, source: str) -> Any:
        # Evaluate source in JavaScript runtime.
        #
        # source -- JavaScript code to evaluate.
        ...

    def call(self, name: str, *args: Any) -> Any:
        # Call a JavaScript function in context.
        #
        # name -- Name of funtion object to call
        # args -- Arguments for the funtion object
        ...

    @abstractmethod
    def is_available(self) -> bool: ...
