# This type stub file was generated by pyright.

# 第三方无类型包（PyExecJS）的最小存根；抽象类以 metaclass=ABCMeta 声明（非继承 ABC），
# 方法参数已按上游签名标注，仍保留下方 pyright 放宽指令以覆盖跨文件引用形态的差异。
# pyright: reportGeneralTypeIssues=none, reportMissingParameterType=none, reportUnknownParameterType=none
# 与 _abstract_runtime_context.pyi 同源的处理：上游的 @six.add_metaclass(ABCMeta) 在存根里改成
# 等价的 metaclass= 写法，以免引入无存根的 six（IDE 单文件检查会报 [import-untyped]）。

from abc import ABCMeta, abstractmethod
from typing import Any

from execjs._abstract_runtime_context import AbstractRuntimeContext

class AbstractRuntime(metaclass=ABCMeta):
    # Abstract base class for runtime class.
    def exec_(self, source: str, cwd: str | None = ...) -> str:
        # Execute source by JavaScript runtime and return all output to stdout as a string.
        #
        # source -- JavaScript code to execute.
        # cwd -- Directory where call JavaScript runtime. It may be ignored in some derived class.
        ...

    def eval(self, source: str, cwd: str | None = ...) -> Any:
        # Evaluate source in JavaScript runtime.
        #
        # source -- JavaScript code to evaluate.
        # cwd -- Directory where call JavaScript runtime. It may be ignored in some derived class.
        ...

    def compile(self, source: str, cwd: str | None = ...) -> AbstractRuntimeContext:
        # Bulk source as a context object. The source can be used to execute another code.
        #
        # source -- JavaScript code to bulk.
        # cwd -- Directory where call JavaScript runtime. It may be ignored in some derived class.
        ...

    @abstractmethod
    def is_available(self) -> bool: ...
