#!/usr/bin/env python3
# 逐模块覆盖率门禁（CI 可调用）。
#
# 读 pytest-cov 写下的 .coverage 数据，对 src/ 下**每一个**模块按各自阈值评一次覆盖率。
# 阈值的事实源只有本文件下方的 MODULE_THRESHOLDS：AGENTS.md 与 pyproject.toml 都刻意不复制
# 那张表（复制出的数值必然与这里漂移）。未登记阈值的模块一律按 GLOBAL_FLOOR 判定，
# 它的取值来源与「为什么不得比全库总闸更宽」见其定义处。
#
# 用法：
#    # 先跑一次带覆盖率的测试
#    pytest --cov=src --cov-report=term-missing
#    python scripts/check_coverage.py
#    # 或指定自定义数据文件
#    python scripts/check_coverage.py --data-file path/to/.coverage
#
# 退出码口径（与 scripts/run_gates.py 一致，必须区分「不达标」与「门禁没跑」）：
#    0  全部模块达标
#    1  有模块低于阈值 / 有模块在数据里查不到（= 覆盖率不达标或数据不含被测模块）
#    2  无 coverage 数据可读（忘了跑 pytest --cov=src、数据文件缺失、JSON 生成失败、
#       数据比源码陈旧、门禁登记表本身指向不存在的模块）
#       —— 这一类**不是**「代码不合格」，但也**绝不是**通过：MIN-19 之前该路径只 WARN，
#          留下「本地没跑 --cov 却以为过闸」的空间；同一口径下「模块查不到」也已由告警
#          改为失败——数据缺失这一路径没有理由继续宽容。
#
# 判定面 = src/ 下全部模块（按文件系统枚举），而不是 MODULE_THRESHOLDS 的键集合：
#   只遍历登记表会让**任何新增的 src/*.py 自动豁免**本门禁，与「新模块必须带测试」相反
#   （表里只有个位数的键，模块数核对：`find src -name '*.py' -not -path '*__pycache__*' | wc -l`）。
#   未登记阈值的模块按 GLOBAL_FLOOR 判定；确需豁免者必须显式写进 GATE_EXEMPT_MODULES
#   并附理由——白名单外没有第三条路。[2026-09-23 MID-2259 前为「只遍历登记表 6 个键」]
#   .coverage 比 src/、tests/ 的源码更旧同样属「没有可判定的数据」（拿旧读数判定 = 门禁
#   自证失效）：新鲜度判据见 _data_is_stale，陈旧一律 rc=2 并给出重跑命令。[MIN-2261 补]

from __future__ import annotations

import argparse
import datetime
import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path, PurePosixPath
from typing import NamedTuple, cast

# 项目根目录（scripts/ 的上一级）：模块枚举与新鲜度比较都以它为基准
ROOT = Path(__file__).resolve().parent.parent

# 兜底数据文件名：优先级（显式 --data-file > $COVERAGE_FILE > 本常量）见 _resolve_data_file，
# 与 coverage 自身取数据文件的顺序一致——本门禁才评得上刚被 pytest --cov 写下的那份数据。
DEFAULT_DATA_FILE = ".coverage"

# 无数据时的统一提示：告诉调用者**下一步命令**，而不是只说「失败了」。
NO_DATA_HINT = (
    "先执行一次带覆盖率的测试再跑本门禁：\n"
    "     .venv/Scripts/python.exe -m pytest -q --cov=src --cov-report=json\n"
    "   （Linux / CI 上为 python -m pytest -q --cov=src --cov-report=json）"
)

# —— 逐模块覆盖率阈值：本表是唯一事实源，AGENTS.md 只链接到此处、不复制数值。
# 新模块不必登记（未登记的按 GLOBAL_FLOOR 判），要放宽必须走 COVERAGE_DEBT / GATE_EXEMPT_MODULES。
MODULE_THRESHOLDS: dict[str, float] = {
    "src/spider.py": 50,
    "src/stream.py": 70,
    "src/utils.py": 80,
    "src/ttwid.py": 85,
    "src/ab_sign.py": 95,
    "src/proxy.py": 50,
}

# 未显式登记阈值的模块所用下限（MID-2259）。取 50.0 与 pyproject
# [tool.coverage.report] fail_under = 50 同口径——本门禁不得比全库总闸更宽，
# 否则「新模块零测试」反而能通过逐模块闸。
GLOBAL_FLOOR = 50.0

# 显式豁免名单（MID-2259 要求的「第三条路」）：键 = 相对路径，值 = 豁免理由。
# 每条理由都必须说明「为什么它不该被本门禁管」，且**不得**为了变绿往里塞普通模块——
# 被豁免的模块仍会打印读数（不参与判定），这样将来取消豁免时缺口立刻可见。
GATE_EXEMPT_MODULES: dict[str, str] = {
    # protoc 生成的桩代码：标注 DO NOT EDIT、随 protobuf 版本重新生成，手改无意义；
    # 与 scripts/check_annotations.py 的 EXCLUDE_FILES 同源（那里也排除它）。
    "src/proto/douyin_pb2.py": "protoc 生成物（DO NOT EDIT，不参与人工补测）"
}


# -- 分层模型（MID-2259 的白名单逻辑，2026-09-23 定稿）-----------------------
# 判定优先级：**登记阈值 > 债务基线 > 全局下限**；豁免名单不参与判定，另设硬校验。
# 设计约束（每条都对应本仓历史上真出过的失效形态）：
#   1. 表必须**默认空**。判定面里除显式豁免的生成物外全部模块都已达标，没有任何模块需要
#      债务基线；DEBT_CEILING = 0 即「要加条目就得先改这里并写明理由」。
#      不设上限的话，本表会和 `--ignore-vuln` 白名单一样，慢慢变成记账本。
#   2. 债务基线**只能低于**全局下限（高于它就等于用白名单藏一个已经达标的模块，
#      还给未来的退化留出空间）。
#   3. 每条必须带 `tracker`（报告条目指针）与 `review_by`（ISO 到期日）。
#      到期即 rc=1 —— 与 `AGENTS.md` 对 pip-audit `--ignore-vuln` 的「临时豁免必须写明到期日」同口径。
#   4. 实际值低于基线 → 失败（棘轮只升不降）；已达全局下限却仍在表内 → 失败（须移出表）。
#   5. 豁免名单的「生成物」理由要**机检**：声明是生成物的文件必须真含生成器标记，
#      否则就是拿一句注释把某个人写的低覆盖模块洗出门禁（rc=2，属门禁配置本身不可信）。
class DebtEntry(NamedTuple):
    # 一条技术债基线。四个字段缺一即视为配置不可信（rc=2，见 _validate_debt_and_exempt）。
    floor: float
    reason: str
    tracker: str  # 登记来源，形如 "CODE_REVIEW_2026-09-22_3.md §7-2"
    review_by: str  # ISO 日期 YYYY-MM-DD；到期后本门禁直接失败


# 当前为空（2026-09-23 补测试后无模块低于全局下限）。加条目须同时上调 DEBT_CEILING 并写理由。
COVERAGE_DEBT: dict[str, DebtEntry] = {}

# 债务基线条数上限（只降不升）
DEBT_CEILING = 0
# 结构不可测豁免条数上限（现仅 1 条 protoc 桩）
EXEMPT_CEILING = 1
# 声称「生成物」的文件必须命中的标记之一（机检豁免理由用）
GENERATED_MARKERS = ("DO NOT EDIT", "Generated by protoc", "protoc-gen")

# 枚举 src/ 时跳过的目录名（编译缓存；它不是可测源码，却会混进 *.py 的通配结果）
_SRC_SCAN_SKIP_DIRS = frozenset({"__pycache__"})

# coverage JSON 报告为嵌套异构 dict，统一以 dict[str, object] 建模，读取处用 cast 收敛
CoverageData = dict[str, object]


def _resolve_data_file(data_file: str | None) -> Path:
    # 定位本次判定实际依赖的 coverage 数据文件（显式参数 > $COVERAGE_FILE > 默认 .coverage）。
    if data_file:
        return Path(data_file)
    env_file = os.environ.get("COVERAGE_FILE", "").strip()
    if env_file:
        return Path(env_file)
    return Path(DEFAULT_DATA_FILE)


def _source_files(root: Path) -> list[Path]:
    # 参与「新鲜度」比较的源码：src/ 与 tests/ 下全部 .py。
    # 为什么含 tests/：本门禁判的是「用例是否覆盖到实现」，而只改用例同样会让
    # .coverage 失效（新增用例把某模块覆盖率抬上去、或删掉用例把覆盖率打下来），
    # 只比 src/ 会漏掉这一半陈旧形态。
    out: list[Path] = []
    for sub in ("src", "tests"):
        base = root / sub
        if not base.is_dir():
            continue
        out.extend(p for p in base.rglob("*.py") if not (_SRC_SCAN_SKIP_DIRS & set(p.parts)))
    return out


def _data_is_stale(data_file: Path, root: Path = ROOT) -> tuple[float, Path, float] | None:
    # 数据文件比源码陈旧时返回 (数据 mtime, 最新源码文件, 其 mtime)，否则 None（MID-2261 补）。
    # 判据用 mtime 而不是「内容哈希」：coverage 只在数据写入时更新 mtime，
    # 任何后续编辑源码/用例都会让其 mtime 落后，方向单一、无歧义；
    # 相等（同一秒内写完）按「不陈旧」处理，避免把「刚跑完就判定」的正常流程打死。
    try:
        data_mtime = data_file.stat().st_mtime
    except OSError:
        # 调用方已在 _get_coverage_json 里判过存在性；这里真读不到就交给上层同样按 rc=2 处理
        return None
    newest: Path | None = None
    newest_mtime = 0.0
    for path in _source_files(root):
        try:
            mtime = path.stat().st_mtime
        except OSError:
            continue
        if mtime > data_mtime and (newest is None or mtime > newest_mtime):
            newest, newest_mtime = path, mtime
    if newest is None:
        return None
    return data_mtime, newest, newest_mtime


def _src_modules(root: Path = ROOT) -> list[str]:
    # src/ 下全部待判定模块（posix 相对路径，排序稳定）。
    # 为什么按文件系统枚举而不是按 coverage 报告的键：报告的键集合本身可能是残缺的
    # （--cov 没生效 / 模块根本没被 import），拿它当判定面就等于「没测到 = 不存在」。
    base = root / "src"
    if not base.is_dir():
        return []
    modules: list[str] = []
    for path in sorted(base.rglob("*.py")):
        if _SRC_SCAN_SKIP_DIRS & set(path.parts):
            continue
        modules.append(path.relative_to(root).as_posix())
    return modules


def _threshold_for(module_path: str) -> tuple[float, str]:
    # 返回 (阈值, 阈值来源)：登记阈值 > 债务基线 > 全局下限。豁免名单在调用侧先处理。
    if module_path in MODULE_THRESHOLDS:
        return MODULE_THRESHOLDS[module_path], "登记"
    debt = COVERAGE_DEBT.get(module_path)
    if debt is not None:
        return debt.floor, f"债务基线 {debt.floor:.0f}%（{debt.review_by} 前须复核）"
    return GLOBAL_FLOOR, f"下限 {GLOBAL_FLOOR:.0f}%"


def _validate_debt_and_exempt(root: Path, today: str | None = None) -> tuple[list[str], list[str]]:
    # 返回 (配置不可信 rc=2, 债务违规 rc=1)。拆两组是因为「表写错了」与「模块不达标」
    # 的修复动作完全不同：前者改表，后者补测试——混在一起会让人拿补表来代替补测试。
    # `today` 仅供用例注入固定日期，生产调用不传（取当日）。
    import datetime

    config_errors: list[str] = []
    violations: list[str] = []

    if len(COVERAGE_DEBT) > DEBT_CEILING:
        violations.append(f"债务基线条数 {len(COVERAGE_DEBT)} 超过上限 {DEBT_CEILING}；上调上限须在 AGENTS.md 写明理由")
    if len(GATE_EXEMPT_MODULES) > EXEMPT_CEILING:
        violations.append(f"豁免条目数 {len(GATE_EXEMPT_MODULES)} 超过上限 {EXEMPT_CEILING}")

    for module, entry in sorted(COVERAGE_DEBT.items()):
        if not entry.reason.strip():
            config_errors.append(f"{module}: 债务基线缺 reason")
        if "CODE_REVIEW" not in entry.tracker or ".md" not in entry.tracker:
            config_errors.append(f"{module}: tracker 必须是报告条目指针（形如 CODE_REVIEW_…md §…）")
        try:
            deadline = datetime.date.fromisoformat(entry.review_by)
        except ValueError:
            config_errors.append(f"{module}: review_by 不是 ISO 日期：{entry.review_by!r}")
            continue
        if entry.floor >= GLOBAL_FLOOR:
            violations.append(f"{module}: 债务基线 {entry.floor:.0f}% 不得低于全局下限 {GLOBAL_FLOOR:.0f}%")
        ref = datetime.date.fromisoformat(today) if today else datetime.date.today()
        if deadline < ref:
            violations.append(f"{module}: 债务基线已于 {entry.review_by} 到期，须复核（补测试或按流程续期）")

    # 豁免理由的「生成物」核对只针对真实仓库根：它验的是**表与仓库文件是否互相印证**，
    # 与本次喂进来的 coverage 报告无关。离线用例传的是 tmp 桩树（里面是空/占位文件），
    # 在那儿核对必然把合理豁免报成虚报——生产入口 `check_coverage()` 用的就是 ROOT，不会漏检。
    if root == ROOT:
        for module, reason in sorted(GATE_EXEMPT_MODULES.items()):
            if "生成物" not in reason and "generated" not in reason.lower():
                continue
            path = root / module
            try:
                text = path.read_text(encoding="utf-8-sig", errors="replace")
            except OSError as exc:
                config_errors.append(f"{module}: 无法读取以核对生成物标记：{type(exc).__name__}")
                continue
            if not text.strip():
                continue
            if not any(marker in text for marker in GENERATED_MARKERS):
                config_errors.append(
                    f"{module}: 理由声称生成物，但文件内找不到生成物标记之一 {GENERATED_MARKERS}（虚报豁免）"
                )
    return config_errors, violations


def _get_coverage_json(data_file: str | None, root: Path = ROOT) -> CoverageData:
    # 生成并解析 coverage JSON 报告（判定所需的一切读数都来自这里）。
    #
    # MIN-19（2026-09-21）：数据文件不存在时**立刻**以 rc=2 失败并给出下一步命令。
    # 原实现在这里只打一条 WARN 再继续，随后读到的是「空报告」，最终表现成
    # 「6 个模块查不到」——既把「忘了跑测试」误报成「覆盖率不达标」，也让
    # 「跑过但没带 --cov」这种最常见的形态没有一个指向性的错误。
    resolved = _resolve_data_file(data_file)
    if not resolved.exists():
        print(f"ERROR: 未找到 coverage 数据文件 {resolved.as_posix()}", file=sys.stderr)
        print("       门禁没有可判定的数据 —— 这是「没跑测试」，不是「覆盖率不达标」。", file=sys.stderr)
        print(f"   {NO_DATA_HINT}", file=sys.stderr)
        sys.exit(2)

    # MID-2261 补：数据存在但比源码陈旧 → 同样是「门禁没有可判定的数据」。
    # 本树实测形态：.coverage 停在上一轮全量运行，之后 src/、tests/ 继续被改，
    # 于是逐模块读数评的是**已经不存在的代码**，PASSED 却是真的——假绿里最难发现的一种，
    # 因为连「数据文件存在」这项检查都确实通过了。（coverage json 自身在源码行号错位时
    # 也可能直接报 "No source for code" 而产不出报告，那时会落到下面的 rc=2 分支。）
    stale = _data_is_stale(resolved, root)
    if stale is not None:
        data_mtime, newer, newer_mtime = stale
        print(f"ERROR: coverage 数据文件 {resolved.as_posix()} 比源码陈旧", file=sys.stderr)
        print(
            f"       数据写入于 {_fmt_time(data_mtime)}，而 {_rel(root, newer)} 改于 {_fmt_time(newer_mtime)}",
            file=sys.stderr,
        )
        print("       门禁评的是已过期的读数 —— 这属「数据不可用」，不是「覆盖率不达标」。", file=sys.stderr)
        print(f"   {NO_DATA_HINT}", file=sys.stderr)
        sys.exit(2)

    tmp_path: str | None = None
    try:
        with tempfile.NamedTemporaryFile(suffix=".json", delete=False) as tmp:
            tmp_path = tmp.name

        cmd = [sys.executable, "-m", "coverage", "json", "-o", tmp_path]
        if data_file:
            cmd.extend(["--data-file", data_file])

        # 加超时与显式编码：防止 coverage 挂起卡死 CI，并兼容 Windows 非 UTF-8 locale
        try:
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                encoding="utf-8",
                errors="replace",
                timeout=60,
            )
        except subprocess.TimeoutExpired:
            print(f"ERROR: coverage json timed out: {' '.join(cmd)}")
            sys.exit(2)

        if result.returncode != 0:
            # coverage json 可能因全局 fail_under 未达标而返回非零退出码（报告仍已生成），
            # 真正的失败以「JSON 能否生成并解析」为准，此处仅提示不中断。
            # 例外：源码与数据行号错位时的 "No source for code" —— 它产不出报告，
            # 等价于数据陈旧，下面的「JSON 读不出来」分支会以 rc=2 + 重跑命令收口。
            print(f"WARN: coverage json exited with code {result.returncode}:\n{result.stderr}", file=sys.stderr)

        try:
            with open(tmp_path, encoding="utf-8") as f:
                report = cast(CoverageData, json.load(f))
        except OSError, ValueError:
            # 数据文件在、JSON 却读不出来：等价于「无可用数据」，同样硬失败（rc=2）。
            print(f"ERROR: failed to read coverage json report: {tmp_path}", file=sys.stderr)
            print(f"       数据文件 {resolved.as_posix()} 存在但报告不可解析。{NO_DATA_HINT}", file=sys.stderr)
            sys.exit(2)

        return report
    finally:
        # 无论成功、失败还是提前退出，都清理临时文件
        if tmp_path:
            Path(tmp_path).unlink(missing_ok=True)


def _fmt_time(ts: float) -> str:
    # 把 mtime 渲染成可读时间戳（诊断信息用；不参与判定）
    return datetime.datetime.fromtimestamp(ts).strftime("%Y-%m-%d %H:%M:%S")


def _rel(root: Path, path: Path) -> str:
    # 诊断信息里尽量打相对路径，绝对路径只在跨盘时出现
    # （Windows 上 Path.relative_to 遇到不同盘符会抛 ValueError）
    try:
        return path.relative_to(root).as_posix()
    except ValueError:
        return path.as_posix()


def evaluate_report(coverage_data: CoverageData, root: Path = ROOT) -> int:
    # 判定核心：吃一份 coverage JSON 报告 dict，对 **src/ 下全部模块**（按文件系统枚举）
    # 逐个评阈值，返回 0 达标 / 1 不达标 / 2 门禁自身失效（含 sys.exit(2) 提前退出）。
    #
    # 为什么单独拆成这个纯判定函数（MID-2261 的「零回归锁」根因之一）：
    # 判定与「跑 coverage 子进程」耦在一个函数里时，单元测试只能靠真数据文件驱动，
    # 于是本门禁长期无人可测——「谓词拿不到输入就返回通过」的形态（files 为空、
    # 模块压根没登记）从来没有回归锁。拆开后，用例可以直接喂构造好的报告 dict 验证
    # 「删掉某条 fail-closed 判据就变红」，而不必跑全量 pytest。
    files = cast(dict[str, CoverageData], coverage_data.get("files", {}))
    if not files:
        # 「有数据文件但里面一个被测文件都没有」＝ 上一轮 --cov 未生效 / 数据被截断，
        # 与「忘了跑」同属门禁失效：必须硬失败，否则下面只会报「模块查不到」而指错方向。
        print("ERROR: coverage 报告里没有任何被测文件条目（files 为空）", file=sys.stderr)
        print(f"       通常是 --cov=src 未生效或数据文件已损坏。{NO_DATA_HINT}", file=sys.stderr)
        sys.exit(2)

    modules = _src_modules(root)
    if not modules:
        # 枚举不到任何 src/ 模块 = 判定面为空。MIN-19 的口径：门禁「没东西可查」一律非 0，
        # 绝不输出「PASSED: All 0 module(s)」——那正是本文件要消灭的假绿形态。
        print("ERROR: 在 src/ 下没枚举到任何待判定模块（root 解析错位？）", file=sys.stderr)
        print("       判定面为空不等于全部达标。", file=sys.stderr)
        sys.exit(2)

    # 登记表/白名单指向磁盘上不存在的模块 = 门禁配置本身腐烂（模块改名后表没跟着改）。
    # 这与「某模块覆盖率不达标」是两类问题，按 rc=2 处理，逼人去改表而不是加测试。
    module_set = set(modules)
    stale_entries = sorted(
        [m for m in MODULE_THRESHOLDS if m not in module_set]
        + [m for m in GATE_EXEMPT_MODULES if m not in module_set]
        + [m for m in COVERAGE_DEBT if m not in module_set]
    )
    if stale_entries:
        print("ERROR: 覆盖率登记表指向 src/ 下不存在的模块（门禁配置已腐烂）:", file=sys.stderr)
        for entry in stale_entries:
            print(f"   - {entry}", file=sys.stderr)
        print(
            "       模块改名/删除时必须同步 MODULE_THRESHOLDS / GATE_EXEMPT_MODULES / COVERAGE_DEBT。",
            file=sys.stderr,
        )
        sys.exit(2)

    # 表本身的合规性先于读数判定：理由不全 / tracker 缺失 / 日期不合法 = 门禁不可信 → rc=2。
    debt_config, debt_violations = _validate_debt_and_exempt(root)
    if debt_config:
        print("ERROR: 覆盖率白名单配置不可信（缺理由 / 指针不合法 / 生成物标记核对失败）:", file=sys.stderr)
        for line in debt_config:
            print(f"   - {line}", file=sys.stderr)
        sys.exit(2)

    failures: list[tuple[str, float, float, str]] = []
    passes: list[tuple[str, float, float, str]] = []
    missing_modules: list[str] = []
    exempt: list[tuple[str, float]] = []

    for module_path in modules:
        if module_path in GATE_EXEMPT_MODULES:
            file_data = _find_module_coverage(coverage_data, module_path)
            pct = _percent(file_data) if file_data is not None else 0.0
            exempt.append((module_path, pct))
            continue
        threshold, source = _threshold_for(module_path)
        file_data = _find_module_coverage(coverage_data, module_path)

        if file_data is None:
            missing_modules.append(module_path)
            continue

        coverage_pct = _percent(file_data)

        # 棘轮的第四面：已达全局下限的模块不得继续躺在债务表里——那等于给未来的
        # 覆盖率退化预留了一段「合法空间」，与本表「只用于记录已知缺口」的定位相反。
        debt = COVERAGE_DEBT.get(module_path)
        if debt is not None and coverage_pct >= GLOBAL_FLOOR:
            debt_violations.append(
                f"{module_path}: 实测 {coverage_pct:.1f}% 已达全局下限 {GLOBAL_FLOOR:.0f}%，须从 COVERAGE_DEBT 移出"
            )

        if coverage_pct >= threshold:
            passes.append((module_path, coverage_pct, threshold, source))
        else:
            failures.append((module_path, coverage_pct, threshold, source))

    # 读数一律打印（含豁免项），这样将来取消豁免时缺口立刻可见
    print("=" * 60)
    print(f"Per-module coverage gate（判定面 = src/ 全部 {len(modules)} 个模块，未登记阈值按下限 {GLOBAL_FLOOR:.0f}%）")
    print("=" * 60)

    if passes:
        print(f"\n[PASS] {len(passes)} module(s) meet threshold:")
        for module, pct, threshold, source in passes:
            print(f"   {module:38s} {pct:5.1f}%  (>= {threshold:.0f}%, {source})")

    if exempt:
        print(f"\n[EXEMPT] {len(exempt)} module(s) 显式豁免（不参与判定，读数仅供复核）:")
        for module, pct in exempt:
            print(f"   {module:38s} {pct:5.1f}%  —— {GATE_EXEMPT_MODULES[module]}")

    if missing_modules:
        print(f"\n[FAIL] {len(missing_modules)} module(s) missing from coverage data:")
        for module in missing_modules:
            print(f"   {module}")
        # 模块在覆盖率数据里查不到，通常意味着 .coverage 未采集到它、或 --cov=src 未生效。
        # 这是「门禁失效」而非「达标」，必须判失败——否则会输出
        # 「PASSED: All 0 module(s) meet coverage threshold」的假绿。
        print("       （查不到即视为门禁失效，按失败处理；确属不可测的生成物请写进 GATE_EXEMPT_MODULES 并附理由）")

    if COVERAGE_DEBT:
        print(f"\n[DEBT] {len(COVERAGE_DEBT)} module(s) 走债务基线（条数上限 {DEBT_CEILING}，只降不升）:")
        for module in sorted(COVERAGE_DEBT):
            debt_entry = COVERAGE_DEBT[module]
            print(
                f"   {module:38s} 基线 {debt_entry.floor:5.1f}%  来源 {debt_entry.tracker}｜{debt_entry.review_by} 前复核"
            )
            print(f"       理由：{debt_entry.reason}")

    if failures or missing_modules or debt_violations:
        if failures:
            print(f"\n[FAIL] {len(failures)} module(s) below threshold:")
            for module, pct, threshold, source in failures:
                deficit = threshold - pct
                print(f"   {module:38s} {pct:5.1f}%  (>= {threshold:.0f}%, {source})  <- {deficit:.1f}% short")
        if debt_violations:
            # 到期未复核 / 超条数上限 / 基线高于下限 / 达标却赖在表内：都不该被「补个测试」糊过去，
            # 它们是白名单机制自身的失效，留着就会一步步退化成记账本。
            print(f"\n[FAIL] {len(debt_violations)} 项白名单违规:")
            for line in debt_violations:
                print(f"   {line}")
        print(f"\n{'=' * 60}")
        print(
            f"FAILED: {len(failures)} module(s) below threshold, {len(missing_modules)} module(s) missing from data"
            + (f", {len(debt_violations)} whitelist violation(s)" if debt_violations else "")
        )
        print(f"{'=' * 60}")
        return 1

    print(f"\n{'=' * 60}")
    print(f"PASSED: All {len(passes)} module(s) meet coverage threshold")
    print(f"{'=' * 60}")
    return 0


def _find_module_coverage(coverage_data: CoverageData, module_path: str) -> CoverageData | None:
    # 在 JSON 报告里定位某模块的读数。报告键的形态不固定（相对 / 绝对 / Windows 反斜杠），
    # 所以匹配规则必须紧到「只可能命中这一个模块」——宽松一档就是拿别的文件的读数评它。
    files = cast(dict[str, CoverageData], coverage_data.get("files", {}))

    # 第一级：报告键与登记表里的相对路径完全相同
    if module_path in files:
        return files[module_path]

    # 第二级（现规则）：**整段模块路径（含 src/）必须出现在报告键的尾部**，分隔符按 POSIX
    # 归一后再比。为什么不能更宽，看这条被收紧两次的历史：
    #   [2026-09-12 审查 6.7] 原实现按**纯文件名**命中（`Path(file).name == Path(module).name`），
    #     于是 tests/utils.py、vendor 下的同名模块都能顶掉 src/utils.py 的读数——门禁拿别人的
    #     覆盖率判通过 = 静默变绿；
    #   [2026-09-23 MID-2261] 6.7 那版仍留一条「去 src/ 前缀 + endswith('/文件名')」的尾部规则，
    #     于是 "tests/utils.py" 照样命中 "src/utils.py"（本仓两处同名模块真实存在）——同一形态
    #     换了个入口而已。故现规则要求整段路径（含 src/）出现在键尾。
    module_norm = Path(module_path).as_posix()

    def _posix(key: str) -> str:
        return key.replace("\\", "/")

    if "/" not in module_norm:
        # 第三级（唯一允许按文件名匹配的情形）：登记表写的就是纯文件名时，仍限定父目录为
        # src 或项目根——不再无门槛接受任意同名文件
        for file_path, file_data in files.items():
            file_norm_path = PurePosixPath(_posix(file_path))
            if file_norm_path.name == module_norm and file_norm_path.parent.name in ("src", ""):
                return file_data
        return None

    for file_path, file_data in files.items():
        key = _posix(file_path)
        # 相等 = 相对键（"src/x.py"）；尾部匹配 = 绝对键（"D:/repo/src/x.py"、"/__w/repo/src/x.py"），
        # 且必须以 "/" 边界起始，避免 "mysrc/utils.py" 这类前缀粘连命中
        if key == module_norm or key.endswith("/" + module_norm):
            return file_data

    return None


def _percent(file_data: CoverageData) -> float:
    # 取单文件覆盖率；缺 summary / 类型异常一律按 0 处理（保守侧：拿不到读数不得当成满分）
    summary = cast(CoverageData, file_data.get("summary", {}))
    raw = cast(object, summary.get("percent_covered", 0.0))
    return float(cast(float, raw))


def check_coverage(data_file: str | None = None, root: Path = ROOT) -> int:
    # 门禁入口：解析数据文件 → 生成/读取 coverage JSON → 交给 evaluate_report 判定。
    # 返回 0 达标 / 1 不达标；rc=2 的三类「门禁没跑」形态在 _get_coverage_json 与
    # evaluate_report 内部直接 sys.exit(2)（数据缺失 / 数据陈旧 / 报告为空 / 登记表腐烂）。
    coverage_data = _get_coverage_json(data_file, root)
    return evaluate_report(coverage_data, root)


def main() -> None:
    parser = argparse.ArgumentParser(description="Per-module coverage gate check")
    _ = parser.add_argument(
        "--data-file",
        type=str,
        default=None,
        help="Path to .coverage data file (auto-detected by default)",
    )
    args = parser.parse_args()
    sys.exit(check_coverage(data_file=cast(str | None, args.data_file)))


if __name__ == "__main__":
    main()
